"""init

Revision ID: ba2cc25136bf
Revises: 
Create Date: 2025-02-17 23:27:47.040668

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = 'ba2cc25136bf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dim_address',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('street_address', sa.String(length=1000), nullable=False),
    sa.Column('city', sa.String(length=500), nullable=False),
    sa.Column('state', sa.String(length=500), nullable=False),
    sa.Column('postal_code', sa.String(length=20), nullable=False),
    sa.Column('country', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('modified_by', sa.String(length=254), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dim_contact',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('phone_number', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('modified_by', sa.String(length=254), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dim_product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('category_label', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('quantity_available', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('modified_by', sa.String(length=254), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dim_partner',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('contact_person', sa.String(length=200), nullable=True),
    sa.Column('address_id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('modified_by', sa.String(length=254), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['address_id'], ['dim_address.id'], ),
    sa.ForeignKeyConstraint(['contact_id'], ['dim_contact.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dim_warehouse',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('address_id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('modified_by', sa.String(length=254), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['address_id'], ['dim_address.id'], ),
    sa.ForeignKeyConstraint(['contact_id'], ['dim_contact.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fact_order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=200), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('partner_id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_by', sa.String(length=254), nullable=False),
    sa.ForeignKeyConstraint(['partner_id'], ['dim_partner.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['dim_product.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['dim_warehouse.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('spt_fallback_usg')
    op.drop_table('spt_monitor')
    op.drop_table('spt_fallback_dev')
    op.drop_table('spt_fallback_db')
    op.drop_table('MSreplication_options')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('MSreplication_options',
    sa.Column('optname', sa.NVARCHAR(length=128, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('value', mssql.BIT(), autoincrement=False, nullable=False),
    sa.Column('major_version', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('minor_version', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('revision', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('install_failures', sa.INTEGER(), autoincrement=False, nullable=False)
    )
    op.create_table('spt_fallback_db',
    sa.Column('xserver_name', sa.VARCHAR(length=30, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('xdttm_ins', sa.DATETIME(), autoincrement=False, nullable=False),
    sa.Column('xdttm_last_ins_upd', sa.DATETIME(), autoincrement=False, nullable=False),
    sa.Column('xfallback_dbid', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=30, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('dbid', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('status', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('version', sa.SMALLINT(), autoincrement=False, nullable=False)
    )
    op.create_table('spt_fallback_dev',
    sa.Column('xserver_name', sa.VARCHAR(length=30, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('xdttm_ins', sa.DATETIME(), autoincrement=False, nullable=False),
    sa.Column('xdttm_last_ins_upd', sa.DATETIME(), autoincrement=False, nullable=False),
    sa.Column('xfallback_low', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('xfallback_drive', sa.CHAR(length=2, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('low', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('high', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=30, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('phyname', sa.VARCHAR(length=127, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False)
    )
    op.create_table('spt_monitor',
    sa.Column('lastrun', sa.DATETIME(), autoincrement=False, nullable=False),
    sa.Column('cpu_busy', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('io_busy', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('idle', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('pack_received', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('pack_sent', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('connections', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('pack_errors', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('total_read', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('total_write', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('total_errors', sa.INTEGER(), autoincrement=False, nullable=False)
    )
    op.create_table('spt_fallback_usg',
    sa.Column('xserver_name', sa.VARCHAR(length=30, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('xdttm_ins', sa.DATETIME(), autoincrement=False, nullable=False),
    sa.Column('xdttm_last_ins_upd', sa.DATETIME(), autoincrement=False, nullable=False),
    sa.Column('xfallback_vstart', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('dbid', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('segmap', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('lstart', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('sizepg', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('vstart', sa.INTEGER(), autoincrement=False, nullable=False)
    )
    op.drop_table('fact_order')
    op.drop_table('dim_warehouse')
    op.drop_table('dim_partner')
    op.drop_table('dim_product')
    op.drop_table('dim_contact')
    op.drop_table('dim_address')
    # ### end Alembic commands ###
